server:
  port: 7979

spring:
  jpa:
    database: H2
    hibernate:
      ddl-auto: false
  datasource:
    url: jdbc:h2:mem:test;MODE=Oracle
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    schema: classpath:data.sql
  application:
    name: exchange-service
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
 
